### ISSUE TITLE
IE11 - IndexSzeError

### ISSUE THREAD

**Issue by andrejkaurin** [yuku-t/jquery-textcomplete#108]
Demo on http://yuku-t.com/jquery-textcomplete/ 
is throwing error in IE 11.
http://prntscr.com/4ga7ve

**Comment by yuku-t** [comment]
`Textarea` object was divided into `IETextarea` and `Textarea` objects long long time ago. Event though I'm not sure it still exists, let me close this issue. If it still exists, feel free to drop me a line. thanks.
