### ISSUE TITLE
Use different ajax sources

### ISSUE THREAD

**Issue by mdmoura** [yuku-t/jquery-textcomplete#114]
Hello,

I was checking the first example of JQuery-TextComplete.

Is it possible to show Autocomplete with three different Ajax sources?

:source1: :source2: :source3:

So in each line the first 3 would call a specific ajax source. 

If it is not possible with : so I could use 3 different patterns:

@source1 :source2 /source3

And if possible after the third the Autocomplete wouldn't work.

Can this be done?

Thank You,
Miguel

**Comment by sahanDissanayake** [comment]
@yuku-t , :+1:  for this question

I need the same functionality,

To load data form a remote source,

For example when I just typed your name on Github your name was loaded from a ajax request

```javascript
@yuku-t 
```

**Comment by yuku-t** [comment]
Sorry for my late reply. If I'm standing on your situation:

```js
[
  { // cities strategy. it priors to countries strategy
    match: /(:\w+:)\s+:(\w*)$/,
    search: function (term, callback) {
      // request to /getcountries?q=...
    }
  },
  { // countries strategy
    match: /(^|\s+):(\w*)$/,
    search: function (term, callback) {
      // request to /getcities?q=...
    }
  }
]
```
