### ISSUE TITLE
IE8 textarea: Droplist position is off for completions on lines other than the first

### ISSUE THREAD

**Issue by JensGabe** [yuku-t/jquery-textcomplete#124]
When showing the completions dropdown in a textarea in IE8, the droplist is shown at the correct position when the carret is on the first line (if the line is wrapped - i.e. the carret is visiually on the second line, but no CR/LF is in the content, then the position is still correct).
After adding a CR/LF to the content the and positioning the carret after this CR/LF the droplist position shows up at a lower position than it should (looks like its about a line-height too low).
This gets lower and lower for each CR/LF added.

**Comment by yuku-t** [comment]
I'm not sure whether the bug is fixed, but Microsoft had already stopped supporting IE8. So I close the issue. Thanks for the comments though!
