### ISSUE TITLE
recognise spaces

### ISSUE THREAD

**Issue by martinlawuk** [yuku-t/jquery-textcomplete#126]
Currently i can type @ and it display my list of values which then highlight using the overlay when selected. What you cannot do is have a space in a value so "@My value" would only highlight "@my". I would like the whole value to highight and recognise the spaces.

Does anyone know if this is possible?

**Comment by alexanderdickson** [comment]
It would be good if overlay plugin could be fed a value of valid offsets to highlight, so we don't need to try and guess later using a regex, list of strings etc

**Comment by yuku-t** [comment]
Close this because it is overlay's issue
