### ISSUE TITLE
JS error using two textcompletes on one page

### ISSUE THREAD

**Issue by eugene-rozov** [yuku-t/jquery-textcomplete#130]
Steps to reproduce:
1. Go to demo page http://yuku-t.com/jquery-textcomplete/ and scroll to 'Apply to Multiple Textareas' example.
2. Put in the first text area word 'test'.
3. Click on the second text area and type 'ap'. Popup with suggestion 'apple' will appear. Click on it.
You will see JS error at the method _onClick, line 470: this.completer.select(datum.value, datum.strategy);

Checked in chrome and safari.

**Comment by grofit** [comment]
Sad Panda, just realized this too...

**Comment by mwynholds** [comment]
I am seeing this issue, and have noticed that a for every textcomplete dropdown you define on a a page, a mousedown and mouseup event are being attached to the single ul.dropdown-menu DOM node.  When you click on a dropdown menu item, all of those mousedowns are being fired, one at a time, starting with the first one that rendered.  If you are not clicking in that specific drop down, then this.data is empty and you wind up with the JS error.

I'm not sure what the best fix is, but I was able to fix this locally by adding the following code to the _onClick function (within the dropdown.js file):

```
if (this.data.length === 0) {
  return true;
}
```

This will let the drop downs that are not being utilized just drop the event through to the next one.  Eventually it will get to the right down down and voila, everything works.

**Comment by yuku-t** [comment]
Fixed by #180
