### ISSUE TITLE
Knowing what was selected

### ISSUE THREAD

**Issue by Nadoedalo** [yuku-t/jquery-textcomplete#131]
Is there any chance to know what was selected?
For example I have two sources that person can choose data from. And from one source this person can choose only once per field. I want to have a tag on that field and catch it at select event.
How can i do that?
Just for now it is done with regexp check of selected value.

**Comment by alexanderdickson** [comment]
I think I might be trying to get this plugin to do more than it was designed for, for example, when using it to do user mentions, I'd like to know if the "mentioned user" was deleted (i.e. the text was backspaced).

This would be quite difficult from what I can understand, as the plugin doesn't keep around a list of values it has matched etc

**Comment by yuku-t** [comment]
>  I'd like to know if the "mentioned user" was deleted

It is out of the plugin's scope. :cry:
