### ISSUE TITLE
Auto focus of textarea is not pulling autocompletion.

### ISSUE THREAD

**Issue by valishah** [yuku-t/jquery-textcomplete#135]
Hi , I have a script in which i'm making focus of textarea as $("#textarea2").focus(). After calling this statement i couldn't able to see the dropdown list of auto completion. Is there any configuration i'm missing in it ?

**Comment by yuku-t** [comment]
Sorry for my late reply. jquery-textcomplete listens keyup event then start completing, so please tryl `.focus().keyup()`
