### ISSUE TITLE
Allow input[type=text]

### ISSUE THREAD

**Issue by storeman** [yuku-t/jquery-textcomplete#140]
Sometimes I like to have the awesome textcomplete plugin to work on input[type=text] elements. Because I want a certain part of the content to be completed, a full auto-completer would not work here.

This check is build in and throws an Error. It should be configurable or just allow input[type=text] besides the ContentEditable and textarea.

**Comment by pafcu** [comment]
:+1:

**Comment by pafcu** [comment]
Fixed in 6735d63059c28e1c84d0105f640fbcd35f81e0ba
