### ISSUE TITLE
Error occurs when I place the autocomplete.js inside the head tag.

### ISSUE THREAD

**Issue by mithundebnath** [yuku-t/jquery-textcomplete#146]
Hello Sir,
Thanks for this wonderful plug in. Sir I am facing a problem. If I include the 
```<script src="js/jquery.textcomplete.js"></script>``` inside the ```<body>...</body>``` tag then plugin works fine. But What my requirement is to place the```<script src="js/jquery.textcomplete.js"></script>``` inside the ```<head>...</head>``` tag. Now If i do so then the plugin doesn't work.I tried to find out why and got this.
```if (typeof jQuery === 'undefined') {```
   ```throw new Error('jQuery.textcomplete requires jQuery');
}``` 
If I place ```<script src="js/jquery.textcomplete.js"></script>``` inside the ```<head>...</head>``` tag then it throws this error as it satisfies the if conditon.
What should I do to solve this problem? I need to place the ```jquery.textcomplete.js``` plugin inside the ```<head></head>``` tag.

**Comment by yuku-t** [comment]
Hi @mithundebnath 
Sorry for my late reply.
It seems that this plugin is loaded *before* jQuery is loaded. So please make sure that jQuery is loaded *ahead* like this.

```html
<!-- NG -->
<head>
  <script src="path/to/jquery.textcomplete.js"></script>
  <script src="path/to/jquery.js"></script>
</head>

<!-- OK -->
<head>
  <script src="path/to/jquery.js"></script>
  <script src="path/to/jquery.textcomplete.js"></script>
</head>
```

**Comment by mithundebnath** [comment]
Hello Sir,
Thanks for the response and sorry for the late as I went to home.This solution is working.Thanks for the desired solution.
