### ISSUE TITLE
Add minimum characters before performing textcomplete

### ISSUE THREAD

**Issue by mark22** [yuku-t/jquery-textcomplete#148]
Is it possible to add minimum character support after the @ tag ?

I am running a query on my server to search for the tags, but I am getting excessive hits from when the @ is first placed and there is no characters, we are just doing empty searches which is wasting resources.  

It would be a great improvement if the search would only occur after a user definied minimum # of characters after the @, for example 3 or 4 or whatever is defined.

Thank you!

**Comment by pafcu** [comment]
I don't think that's a problem if jquery-textcomplete, rather it's about how your site is using it. How many characters you have to type before completion depends on the regular expression you are using. Just use something like /(^|\s)(@\w{3})/ (untested) to match an @ followed by at least three characters.

**Comment by yuku-t** [comment]
Hi @mark22 
I think fixing regular expression is the best way to solve your problem like @pafcu wrote (thanks @pafcu!).

Another solution is fixing search function like this:

```js
search: function (term, callback) {
    if (term.length < 3) { callback([]); }
    // invoke XHR request and callback with API response
}
```

**Comment by wbinnssmith** [comment]
I've run into this particular need too, and one thing this solution can't handle is showing a message like "Type more..." to inform the user that they haven't met the minimum character requirement for suggestions. Also, this solution makes it impossible to determine the difference between matching no results and not meeting the minimum requirement.

A workaround would be to implement an additional search strategy using a regex for text below the minimum count, but this feels like we're stacking hacks ontop of each other.

Would you be open to considering a solution as a patch to add this to the core library?
