### ISSUE TITLE
Chinese inpu

### ISSUE THREAD

**Issue by night1008** [yuku-t/jquery-textcomplete#156]
hello,can this support Chinese input?

**Comment by yuku-t** [comment]
Hi @night1008 

Yes, it can. It simply uses a regular expression to detect words in associated textarea. So, please create a regular expression which matches to 中文 as you expect.

```js
match: /(我是)$/,
search: function (term, callback) {
    callback(['中国人', '日本人']);
},
replace: function (word) {
    return '$1' + word;
}
```

![image](https://cloud.githubusercontent.com/assets/96157/6458322/98a075a2-c1c5-11e4-96cd-9bf15a2dfc13.png)

**Comment by night1008** [comment]
Thank you for such a quick response,you are very big help for me.

**Comment by night1008** [comment]
Hi, can I dynamically change the "match" regex,for example,I want to match a string's last few characters, such as: /(.{param})(\S{2,})$/, the param is a dynamical number, what can I do?

**Comment by yuku-t** [comment]
I understand your motivation. I'll make `match` option be able to get both a regex and a function which returns a regexp.

**Comment by night1008** [comment]
nice ! You are my role model !
