### ISSUE TITLE
Unicode not work

### ISSUE THREAD

**Issue by namaljayathunga** [yuku-t/jquery-textcomplete#160]
I used unicode string array. but it not worked for me. How can I handle that issue. thank.

**Comment by yuku-t** [comment]
#156 may help you.

**Comment by namaljayathunga** [comment]
thanks yuku-t, also stackoverflow answer was helpful me. thanks.
http://stackoverflow.com/questions/29124968/jquery-textcomplete-not-work-with-unicode-and-remove-space/29126775

**Comment by namaljayathunga** [comment]
I have an idea from the google input tool. it is suggest word with the number order. When suggesting, we can enter it's number. then word replace easily. Also thank for jquery-textcomplete. http://www.google.com/intl/si/inputtools/try/
