### ISSUE TITLE
contenteditable is not working in IE8

### ISSUE THREAD

**Issue by mahesravs** [yuku-t/jquery-textcomplete#162]
Hi,
Hope you are doing great.
I used textcomplete contenteditable div.
With this plugin my application is working perfectly in FF but not in IE8.
Could you please help me in resolving this issue.

**Comment by yuku-t** [comment]
I'm not sure whether the bug is fixed, but Microsoft had already stop supporting IE8. So I close the issue. Thanks for the comments though!
