### ISSUE TITLE
What does adapter class should contain?

### ISSUE THREAD

**Issue by signalarun** [yuku-t/jquery-textcomplete#164]
var option = {
  appendTo:  appendToElement, // $('body')
  height:    heightNumber,    // undefined
  maxCount:  maxCountNumber,  // 10
  placement: placementStr,    // ''
  header:    headerStrOrFunc, // undefined
  footer:    footerStrOrFunc, // undefined
  zIndex:    zIndexStr,       // '100'
  debounce:  debounceNumber,  // undefined
  adapter:   adapterClass,    // undefined
  className: classNameStr     // ''
};

**Comment by yuku-t** [comment]
Sorry for my late reply.
I started implementing v2 with completely new code base using external [core package](https://github.com/yuku-t/textcomplete). I'll provide a document for the issue. yuku-t/textcomplete#34
