### ISSUE TITLE
css .dropdown-menu is conflicting with twitter bootstrap .dropdown-menu

### ISSUE THREAD

**Issue by changeweb** [yuku-t/jquery-textcomplete#166]
I would suggest to use `.dropdown-menu-textcomplete` class instead of `.dropdown-menu`. It'll be unique for Textcomplete.

**Comment by yuku-t** [comment]
hi, thanks for your suggestion. btw it is intended.

**Comment by changeweb** [comment]
But it affects style of other dropdowns. If you do something like this, you can have both the effects of bootstrap dropdown and textcomplete without affecting other dropdowns in the page. If you want I can send a pull request.

textcomplete.css

      /* Sample */

     .dropdown-menu-textcomplete {
        border: 1px solid #ddd;
        background-color: white;
     }

     .dropdown-menu-textcomplete li {
        padding: 2px 5px;
     }

    .dropdown-menu-textcomplete li:first-child {
       border-top: none;
     }

     .dropdown-menu-textcomplete li:hover,
     .dropdown-menu-textcomplete .active {
         background-color: rgb(110, 183, 219);
      }


      /* SHOULD not modify */

     .dropdown-menu-textcomplete {
        list-style: none;
        padding: 0;
        margin: 0;
     }

    .dropdown-menu-textcomplete a:hover {
       cursor: pointer;
     }

textcomplete.js

     findOrCreateElement: function (option) {
      var $parent = option.appendTo;
      if (!($parent instanceof $)) { $parent = $($parent); }
      var $el = $parent.children('.dropdown-menu .dropdown-menu-textcomplete');
      if (!$el.length) {
        $el = $('<ul class="dropdown-menu dropdown-menu-textcomplete"></ul>').css({
            display: 'none',
            left: 0,
            position: 'absolute',
            zIndex: option.zIndex
         }).appendTo($parent);
        }
        return $el;
      }

**Comment by tomsommer** [comment]
I agree. This is a problem. Please don't manipulate bootstrap CSS classes.

**Comment by yuku-t** [comment]
@tomsommer the ul element has `.textcomplete-dropdown` class. you can use it.

**Comment by tomsommer** [comment]
That's not the problem, the problem is that you manipulate bootstraps `.downdown-menu`

**Comment by yuku-t** [comment]
@tomsommer This plugin is 100% JavaScript. It does not contain CSS, isn't it? If `.dropdown-menu` is broken, it's caused by your CSS. It's not my fault.

![image](https://cloud.githubusercontent.com/assets/96157/15856623/a5c0981e-2cf1-11e6-925c-dabfc8b5bcde.png)

BTW I've added `dropdownClassName` option and release v1.5.0. Now you can change the class attribute of the ul element. See example: http://yuku-t.com/jquery-textcomplete/#change-dropdown-class-name

**Comment by tomsommer** [comment]
What?

https://github.com/yuku-t/jquery-textcomplete/blob/05dbf13e0e4c16702d613ec5fbdcac4904809fae/dist/jquery.textcomplete.css#L3

**Comment by yuku-t** [comment]
Ah, I forgot the file :(

But, you know, it's just a [sample](https://github.com/yuku-t/jquery-textcomplete/blob/add20da651acc309535efff0d75860e64d8d8b5a/dist/jquery.textcomplete.css#L1). This plugin does not require it.

I removed the sample css file from the repository to let copy and paste programmers, including you, use this plugin correctly.
