### ISSUE TITLE
TypeError: datum is undefined

### ISSUE THREAD

**Issue by djangosdk** [yuku-t/jquery-textcomplete#168]
Hi, I was facing an error after I used textComplete in My application. at line ```	this.completer.select(datum.value, datum.strategy);```
This happens when I try to select textCompelte dropdown with mouse. With keyboard it is ok always.

I looked at your demo page and found same issue which i was facing.IMO this does not happen always , only happens when there more than one textCompletes (could be wrong but this is what i suspect)

Example:
at url http://yuku-t.com/jquery-textcomplete/ demo for Use with jQuery.overlay , when i press @ and select yuku_t with mouse I get following error on console , 
```
TypeError: datum is undefined
this.completer.select(datum.value, datum.strategy);  (line 518, col 6)
```
![und](https://cloud.githubusercontent.com/assets/4101480/7318054/2d5e6c86-eaa1-11e4-8082-c76e1f73f6e0.png)

This doesnot happen always. If I reload page and try different demo examples on that page then after unknown tries this starts to happen

**Comment by djangosdk** [comment]
I think I fixed this issue by deleting  dropdown-menu which was generated by jquery-textcomplete
and it seems to go away.very strange, shouldnt destroy method remove this ul as well , i was calling it before creating textComplete.

I wish ul.dropdown-menu had a class like ul.dropdown-menu.text-complete so one can easily delete specific ul lists.

**Comment by dinodsja** [comment]
How can i fix this ???

**Comment by yuku-t** [comment]
Now dropdown element is automatically removed after `textcomplete('destroy')` 414964f1d. I'm not sure the reported problem is fixed by the commit, but let me close the issue. If it still exists, feel free to comment again. thanks
