### ISSUE TITLE
jQuery-textcomplete not work on contenteditable div?

### ISSUE THREAD

**Issue by namaljayathunga** [yuku-t/jquery-textcomplete#171]
I am working on simple auto complete chrome extension using [jQuery-textcomplete](https://github.com/yuku-t/jquery-textcomplete/blob/master/dist/jquery.textcomplete.js) script. It is working well on most of traditional sites, because they use textarea. It is not working on google+ comment box, facebook comment box and even gmail. Because they only use div tag with htmp5 'contenteditable' option to get user's text also use react in facebook. So jquery selector not working. How can I solve this problem? hear is my selector.

    $("textarea, .editable, textbox, text").textcomplete([{
   	    match: /(^|\S*)([^\u0000-\u007f]{2,}|\w{2,})$/,
    	search: function (term, callback) {
        callback($.map(EnDict, function (word) {
            return word.indexOf(uni_word) === 0 ? word : null;
        }));
    	},
    	replace: function (word) {
         return word + ' ';
	   }
	}]);

check this image.

![enter image description here][1]

  [1]: http://i.stack.imgur.com/yzWb0.jpg

**Comment by namaljayathunga** [comment]
I added [Github repository](https://github.com/namaljayathunga/jquery-textcomplete--chrome-extension), bacause contentediable div work with normaly inside any web page. However when creating the Chrome extension it not support for contentediable div.

**Comment by yuku-t** [comment]
> It is not working on google+ comment box, facebook comment box and even gmail.

Technically, you have to write your own adapter for these input fields, but because they do not provide public APIs to implement such functionality, it is impossible to support them. :(
