### ISSUE TITLE
Case sensitive search

### ISSUE THREAD

**Issue by guibirow** [yuku-t/jquery-textcomplete#173]
I'd like to suggest an update on search function used on examples, instead of use:
```return word.indexOf(term) === 0 ? word : null; ``` //This line is case sensitive
use
```return word.search(new RegExp(term, "i")) === 0 ? word : null;``` //this line is case insensitive

Sample
```
       $('#textareaAutoComplete').textcomplete([
        {
            words: ['apple', 'google', 'facebook', 'github', 'Microsoft'],
            match: /\B:([\-+\w]*)$/,
            search: function (term, callback) {
                callback($.map(this.words, function (word) {
                    return word.search(new RegExp(term, "i")) === 0 ? word : null;
                }));
            },
            replace: function (value) {
                return ':' + value + ': ';
            },
            index: 1
        }]);
```

**Comment by jefferson117** [comment]
This is definitely required for me and has the added benefit of providing "contains" search. Code should however be:
```javascript
 return word.search(new RegExp(term, "i")) != -1 ? word : null
```

**Comment by alexanderdickson** [comment]
Why not just use `toLowerCase()` ?

**Comment by guibirow** [comment]
Sorry the delay, you can use toLowerCase() if you want. But you need to lower the list and the typed word.
With regex you don't care the way the user types and also can add find by regular expression.
It's your choice.

**Comment by yuku-t** [comment]
Sorry for my late reply and thanks for the proposal. Please consider sending a patch against gh-pages branch. Thanks for opening the issue though!
