### ISSUE TITLE
How to use the autocomplete filter to match text after the cursor?

### ISSUE THREAD

**Issue by plato-cambrian** [yuku-t/jquery-textcomplete#174]
My use case is:
```
Given I have a list of channel members
And I type but do not send a message like `hello yuku-t whats up`
When I click in front of `yuku-t`
And I press @
Then the autocomplete menu should show
And the only visible entries should be matching strings
```
The current behavior (at least with my matching regex `/\B@(\w*)$/`) displays the *entire* list of possible matches. It appears that this is because the regex only matches between the last boundary character and the cursor.

You can reproduce this yourself on the [demo page](http://yuku-t.com/jquery-textcomplete/#textarea1), type `abc`, move the cursor to the front, press `:`, and see non-matches.

Can anyone propose a different regex or another solution?

**Comment by yuku-t** [comment]
The plugin does not support such use cases :crying_cat_face: 
By the way, you can do that by something like this:

```js
var $el = $('textarea');
$el.textcomplete([{
  match: /(.*)$/,
  search: function (beforeCursor, callback) {
    var value = $el.val();
    var afterCursor = value.substr(beforeCursor.length);
    callback(getCandidates(beforeCursor, afterCursor);
  },
  index: 1,
  // ...
}]);
```

**Comment by plato-cambrian** [comment]
Thanks @yuku-t. What exactly happens here? When the cursor moves or input happens, the regex is executed, and the first match group is passed to search as beforeCursor?

**Comment by Kurshith** [comment]
Hi yuku-t,

Thanks for the wonderful plugin. Am new to javascript and jquery. The regex /\B@(\w*)$/) triggers auto-complete when typing @. But it also triggers if having more than one @@@. How can I control that, please help me. My use case is, need to show only if the beginning of the word having a single @.

Thanks
