### ISSUE TITLE
Continue to next strategy after a strategy matches but returns no results

### ISSUE THREAD

**Issue by japgolly** [yuku-t/jquery-textcomplete#175]
If strategy A doesn't match term, it will check if strategy B matches.
Problem is when strategy A matches and returns 0 results, it will not continue to strategy B.

**Comment by yuku-t** [comment]
Sorry for my late reply. I understand your motivation but I don't want to implement it to keep the source simple. I think you can do the same thing by merging your strategies into a single strategy.
