### ISSUE TITLE
Option to NOT highlight first item (or any) in the dropdown by default?

### ISSUE THREAD

**Issue by bholub** [yuku-t/jquery-textcomplete#176]
Would it be possible to not highlight/activate any items in the drop down until the user clicks or hits the down arrow? I want the user to be able to hit enter without auto-completing. Thanks!

**Comment by astanley86** [comment]
Yes, I'm also wanting this option.  @bholub Did you figure out how to make this happen?

**Comment by yuku-t** [comment]
Close the issue due to duplication. #228
