### ISSUE TITLE
findOrCreateElement function

### ISSUE THREAD

**Issue by char0n** [yuku-t/jquery-textcomplete#180]
I have a little problem with findOrCreateElement function. I have multiple vendor libraries that creates element with class .dropdown-menu inside the body element. Text-complete will get first element with .dropdown-menu and override it with its own data. This problem can be bypassed with appendTo option, but from various reasons I need to keep my dropdown-menus directly inside the body element.

Is there another approach to this ? If not I  am suggesting following:

1.) introduce new option called e.g. dropdownId
2.) use it inside the findOrCreateElement function

Original function:
```javascript
   findOrCreateElement: function (option) {
      var $parent = option.appendTo;
      if (!($parent instanceof $)) { $parent = $($parent); }
      var $el = $parent.children('.dropdown-menu')
      if (!$el.length) {
        $el = $('<ul class="dropdown-menu"></ul>').css({
          display: 'none',
          left: 0,
          position: 'absolute',
          zIndex: option.zIndex
        }).appendTo($parent);
      }
      return $el;
    }
```

Modified function:
```javascript
   findOrCreateElement: function (option) {
      var $parent = option.appendTo;
      var dropdownId = options.dropdownId || '';
      if (!($parent instanceof $)) { $parent = $($parent); }
      var $el = $parent.children(dropdownId + '.dropdown-menu')
      if (!$el.length) {
        $el = $('<ul class="dropdown-menu" id="'+dropdownId+'"></ul>').css({
          display: 'none',
          left: 0,
          position: 'absolute',
          zIndex: option.zIndex
        }).appendTo($parent);
      }
      return $el;
    }
```

I can send a pull request if this is a way to go. Thanks for any answer.

**Comment by char0n** [comment]
I guess it relates to https://github.com/yuku-t/jquery-textcomplete/issues/130. There can be multiple dropdown menus that can be opened at the same time and they should not collide with each other.

**Comment by char0n** [comment]
Or another approach can be to used `className` option in findOrCreateElement function.

Anybody have some ideas please ?

**Comment by yuku-t** [comment]
Hi @char0n, thanks for opening the issue.

I understand your situation. Now dropdown element has "textcomplete-dropdown" class. 

FYI all textcomplete objects having same `appendTo` share dropdown elements.

**Comment by char0n** [comment]
Thanks for the textcomplete-dropdown class. This should resolve my problem.

Anyway: is there a reason why share the sme dropdown menu ? This will effectively eliminate possibility to have 2 opened text complete dropdown menus. What is the logic behind this ? 

Thanks a lot.
