### ISSUE TITLE
How to restrict the auto-complete, to not allow @@ in a beginning of a word? 

### ISSUE THREAD

**Issue by Kurshith** [yuku-t/jquery-textcomplete#181]
Hi yuku-t,

The regex /\B@(\w*)$/) triggers auto-complete when typing @. But it also triggers if having more than one @@@. How can I control that, please help me. My use case is, need to show only if the beginning of the word having a single @.

Thanks

**Comment by yuku-t** [comment]
hmmm, i think there is no simple solution. if i tackle your problem, i'll do something like this:

```js
{
  regex: /\B(@+)(\w*)$/,
  index: 2,
  search: function (term, callback, match) {
    if (match[1].length != 1) return callback([]);
    // do search
  },
  replace: function (value) {
    return '$1' + value + ' ';
  }
}
```
