### ISSUE TITLE
Inserting mentions programatically

### ISSUE THREAD

**Issue by mir3z** [yuku-t/jquery-textcomplete#185]
Is it possible to insert a mention into the text programmatically at cursor position?

Let's assume I have a text:
`foo bar | baz` where | is a cursor position.

I need a way to insert some mention at cursor position and apply jquery.overlay
`foo bar @example baz`

**Comment by yuku-t** [comment]
Sorry for my late reply.
It seems there is no need to use the jquery-textcomplete plugin to achieve your aim. Please use pure DOM APIs instead.
