### ISSUE TITLE
Dropdown doesn't appear after an autocomplete has completed

### ISSUE THREAD

**Issue by dflynn5008** [yuku-t/jquery-textcomplete#186]
So I have two strategies, one looking for '@' and one looking for '#' if I complete an autocomplete, like @car, and then type an '@' or a "#' afterwards, my dropdown doesn't come up, until I do something else on the keyboard (type, space, backspace)
This behavior happens in the demos here as well. 
Is there a workaround for this so that the drop down comes down after an autocomplete happens?

**Comment by yuku-t** [comment]
Close the issue because I couldn't reproduce the issue with v1.1.0
