### ISSUE TITLE
Get different autocomplete suggestions for words based on their positions?

### ISSUE THREAD

**Issue by yasheshgaur** [yuku-t/jquery-textcomplete#189]
Hey!
Great job with the plugin @yuku-t . I am glad I found it. :smile: 
I, however, have a slightly different autocomplete requirement. I want to give a different set of autocomplete suggestions based the position of the word the textarea. 
I saw that you attach the callback with the text area and hence autocomplete suggestions remain the same for all words in the text area. How do I utilize your plugin to get a different set of words based on the word position. 
I know I can simply attach a different set of words to the text area every time I change to a different word, but that just seems wasteful to me. I hope you will be able to provide a smart solution.

Thanks!

**Comment by fatihzkaratana** [comment]
+1

**Comment by yuku-t** [comment]
Sorry for my late reply.
Search function takes whole textarea's value as the fourth argument. Maybe you can use it to change the behavior.
