### ISSUE TITLE
textcomplete not firing for the first time 

### ISSUE THREAD

**Issue by dropshadow** [yuku-t/jquery-textcomplete#197]
Textcomplete autocompletion not firing for the first time , second time its okay , am using the following code 

    $('#edit-email-template').textcomplete([{
       // match: /(^|\s)(\w{2,})$/,
          match: /\B:([\-+\w]*)$/ ,
        search: function (term, callback) {
             $.getJSON('/notification/findAllUserVariables')
	        .done(function (resp) {
        	    	variables =resp.variable_name;
			alternates = resp.content;
			search=resp.term;
            	 })
        	.fail(function () {
            		callback([]);
        	});
		callback($.map(variables, function (n,i) {
	 		return  i ;
                }));
		
        },
	template: function (value) {
            return  variables[value];
        },
        replace: function (word) { 
                        
            return ' ' + alternates[word] + ' ';
        }
    }]);

**Comment by yuku-t** [comment]
syntax highlight

```js
$('#edit-email-template').textcomplete([{
  // match: /(^|\s)(\w{2,})$/,
  match: /\B:([\-+\w]*)$/ ,
  search: function (term, callback) {
    $.getJSON('/notification/findAllUserVariables')
      .done(function (resp) {
        variables =resp.variable_name;
        alternates = resp.content;
        search=resp.term;
      })
      .fail(function () {
        callback([]);
      });
    callback($.map(variables, function (n,i) {
      return  i ;
    }));
  },
  template: function (value) {
    return  variables[value];
  },
  replace: function (word) { 
    return ' ' + alternates[word] + ' ';
  }
}]);
```

**Comment by yuku-t** [comment]
It seems that you don't call `callback` when `$.getJSON` succeeds to get user variable from remote server. Please call `callback` as something like this:

```js
$.getJSON()
  .done(function (resp) {
    // parepare a parameter using `resp`
    callback(param);
  })
  .fail(function () { ... });
```

**Comment by dropshadow** [comment]
Thanks .
