### ISSUE TITLE
Get the current input/textarea element so generate a lists of words dynamically

### ISSUE THREAD

**Issue by MatthewRiches** [yuku-t/jquery-textcomplete#199]
This is the best and cleanest implementation I've found so far, so thank you very much.

This may be an enhancement, but is there a way to get the originating input/textarea that the textcomplete was triggered on? Essentially I want to generate a list of words based on an attribute of the input/textarea that was triggered, an example might be:

```js
$('.form-control').textcomplete([{
    match: /(^|\s)\$(\w*)$/,
    search: function (term, callback) {
        var elm = $(this); // this is currently not the input
        var words = elm.data('words').split(',');
        callback($.map(words, function (word) {
            return word.indexOf(term) === 0 ? word : null;
        }));
    },
  ...
```

I could create a new instance for each .form-control however with hundreds of inputs on the page I feel it would be far better to have one generic function that computed the words dynamically. I'm hoping there is a variable I can access to get the originator - thanks in advanced for any feedback.

**Comment by yuku-t** [comment]
Hi @MatthewRiches 
Thanks for the comment.
Now you can use `this.el` and `this.$el` in search function :)

**Comment by MatthewRiches** [comment]
Wow thanks.
