### ISSUE TITLE
Allow user to cancel autocomplete

### ISSUE THREAD

**Issue by japgolly** [yuku-t/jquery-textcomplete#201]
I think user should be able to press Escape to remove the autocomplete dropbox.

Imagine valid autocomplete options include `run` and `runt`.
If the user types `run`, the dropdown is visible because `runt` is valid too.
User needs to be able to keep their word `run` and remove the dropdown (I suggest just press Escape key).

**Comment by Petah** [comment]
It does this already, doesn't it?

**Comment by japgolly** [comment]
Oh you're right, I forgot to check `defaultPrevented` in my code. Sorry & Thanks
