### ISSUE TITLE
Uncaught TypeError: $(...).textcomplete is not a function

### ISSUE THREAD

**Issue by dropshadow** [yuku-t/jquery-textcomplete#202]
I am having trouble in showing autocomplete suggestions : 
my js lib files included as follows 
jquery.js (1.13)
jquery.textcomplete.js 
mylib.js (from here am calling textcomplete suggestion as follows )

$('#edit-email-template').textcomplete([{
            // match: /(^|\s)(\w{2,})$/,
            match: /\B:([\-+\w]*)$/,
            search: function (term, callback) {
                $.getJSON('/notification/findAllUserVariables')
                        .done(function (resp) {
                            variables = resp.variable_name;
                            alternates = resp.content;
                            search = resp.term;
                            callback($.map(variables, function (n, i) {
                                return  i;
                            }));
                        })
                        .fail(function () {
                            callback([]);
                        });

            },
            template: function (value) {
                return  variables[value];
            },
            replace: function (word) {

                return ' ' + alternates[word] + ' ';
            }
        }

**Comment by yuku-t** [comment]
> Uncaught TypeError: $(...).textcomplete is not a function

It seems that you are not loading jquery.textcomplete.js correctly. Please load it before executing `$(...).textcomplete` function

**Comment by dropshadow** [comment]
Thanks . I was mistakenly added the same jquery twice after the textcomplete.js causes the problem .
