### ISSUE TITLE
Textcomplete suggestions not working when applied ckeditor plugin

### ISSUE THREAD

**Issue by dropshadow** [yuku-t/jquery-textcomplete#205]
Hi , I applied ckeditor plugin to a textarea , then when i tried to apply textcomplete suggestions its not working , even the ajax request is not going ,

$('#edit-email-template').textcomplete([{
            match: /\B:([\-+\w]*)$/,
            search: function (term, callback) {
                $.getJSON('/notification/findAllUserVariables')
                        .done(function (resp) {
                            variables = resp.variable_name;
                            alternates = resp.content;
                            search = resp.term;
                            callback($.map(variables, function (n, i) {
                                return  i;
                            }));
                        })
                        .fail(function () {
                            callback([]);
                        });
            },
            template: function (value) {
                return  variables[value];
            },
            replace: function (word) {
                return ' ' + alternates[word] + ' ';
            }
        }]);

And  i given 'ckeditor' class  for the textarea , thats all .

**Comment by yuku-t** [comment]
#90 duplicated

**Comment by dropshadow** [comment]
But its not actually resolved my problem . can you give a snapshot on how to do it

**Comment by namaljayathunga** [comment]
+1
