### ISSUE TITLE
Issue when i upgrade from version .6 to .8

### ISSUE THREAD

**Issue by samuraiu** [yuku-t/jquery-textcomplete#207]
Hello. 

I have the following problem, your library is working fine with .6 version, but when i am upgrading to .8 i always get  textcomplete() function not defined.  Now if i look at textcomplete.js i can see that 
this(function at bottom) is added at the beginning, and it seems like the function is not found correcty. Is there anything else i need to do for my code from .6 to work or i only need to replace textcomplete.js file ? 

Thanks for help. 

```js
(function (factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['jquery'], factory);
  } else if (typeof module === "object" && module.exports) {
    var $ = require('jquery');
    module.exports = factory($);
  } else {
    // Browser globals
    factory(jQuery);
  }
```

**Comment by yuku-t** [comment]
probably, you don't load jquery prior to jquery.textcomplete.

```html
<script src="path/to/jquery.js"></script>
<script src="path/to/jquery.textcomplete.js"></script>
```
