### ISSUE TITLE
Returning [object Object]

### ISSUE THREAD

**Issue by mrgreen222** [yuku-t/jquery-textcomplete#216]
When using this snipp:

```
    $('textarea').textcomplete([
    {
        match: /\B:([\-+\w]*)$/,
        search: function (term, callback) {
          callback(term, true);
          $.getJSON('search', { keyword: term })
            .done(function (resp) { callback(resp); })
            .fail(function ()     { callback([]);   });
    },
        replace: function (value) {
            return ':' + value + ': ';
        },
        index: 1
    }
], {
    onKeydown: function (e, commands) {
        if (e.ctrlKey && e.keyCode === 74) { // CTRL-J
            return commands.KEY_ENTER;
        }
    }
});
```

The drop down contains nothing more than:
<img width="186" alt="skarmavbild 2015-11-20 kl 19 49 39" src="https://cloud.githubusercontent.com/assets/15329289/11308673/e0c3ce74-8fbf-11e5-8b05-9df0952eee55.png">

I´am returning the results with json_encode. And from Chrome dev tools i can see that i get a respons with options from `search?keyword=`

Using jQuery 2.1.3

Is it possible to change to AJAX?

EDIT:
And if i continue typing my input that i want, i get `Uncaught TypeError: Cannot use 'in' operator to search for '1' in jquery.js:546`

**Comment by maxdev1** [comment]
Hey,

you get a list of objects from the response, because JavaScript deserialized the incoming JSON. Try logging the values with `console.log` to see what they contain. Then, in your replace function, simply return `value.yourField` to show that value in the auto-complete.

    replace: function (value) {
        return ':' + value.yourField + ': ';
    }

Greets

**Comment by mrgreen222** [comment]
Thanks for your answer!

But, how would I log the values to console.log?

**Comment by maxdev1** [comment]
No problem!

Ah, I see. You must add both a "template" and a "replace" function. In both you must return "value.aktie". The "template" function creates the values that are displayed in the autocomplete; the "replace" function creates the value that is inserted when the users selects a value. See if that works! :-)

**Comment by mrgreen222** [comment]
Thank you so much! It seems to work, kinda...

Now i get the error `Uncaught TypeError: Cannot use 'in' operator to search for '0' in s` and when googling for a solution i find that downgrade jQuery to anything but 2.1.4 would fix this. But no, I have tried all of them with same error, or no function at all.

See this thread: https://github.com/jquery/jquery/issues/2242

It seems to be a problem with DataTables, I don't really know what that even is.
