### ISSUE TITLE
Programmatically closing the dropdown

### ISSUE THREAD

**Issue by maxdev1** [yuku-t/jquery-textcomplete#220]
At the moment there is no function for programmatically closing the dropdown. This workaround makes it possible though:

http://stackoverflow.com/questions/34063831/how-to-close-the-autocomplete-dropdown-of-jquery-textcomplete-programmatically/34063832#34063832

A builtin function for this would be great.

**Comment by yuku-t** [comment]
Thanks for opening the issue. It was enabled by #233
