### ISSUE TITLE
Trigger textcomplete on CTRL-space

### ISSUE THREAD

**Issue by mourad1081** [yuku-t/jquery-textcomplete#226]
Hello (sorry for my probable bad english), 
I do not know how to trigger the textcomplete with CTRL-space like as many IDE's do that. I read the FAQ but didn't find any answer to that. Can you help me ?

(I want that when i do CTRL-space, all words are suggested like an IDE)

**Comment by maxdev1** [comment]
See https://github.com/yuku-t/jquery-textcomplete/blob/master/doc/faq.md#how-to-trigger-textcomplete-manually

Create a keydown-listener on the textfield and programmatically trigger it when the user presses space with control down.

**Comment by yuku-t** [comment]
Yep, please follow the @maxdev1's comment. (thanks @maxdev1 :+1: )
