### ISSUE TITLE
Multiple overlay with one textarea

### ISSUE THREAD

**Issue by romisbim** [yuku-t/jquery-textcomplete#230]
Hi,

Is it possible to have 2 overlay function on the same textarea?

Basic example:
1) I have some words surrounded by pipe | char and want to put in yellow (old selected words with the replace from textcomplete)
2) The researched term in blue when beginning by : or @ (current word to research)

First, thanks for you actual plugin and for the futur answer :)

**Comment by yuku-t** [comment]
please open an issue related to overlaying at yuku-t/jquery-overlay instead. thanks
