### ISSUE TITLE
TypeError: $(...).keypress(...).textcomplete is not a function

### ISSUE THREAD

**Issue by namaljayathunga** [yuku-t/jquery-textcomplete#232]
I know this is previously asked question, but this is deference.  I firstly created example webpage and it worked. Secondly I added jquery-textcomplete to my project that has lot of js files, then above error happened. I think there has js conflict. So I initialized jquery-textcomplete as anonymous function like bellow but error not solved. Plz help me, How can I solve this problem. Thanks.

```js
(function($){
            $('textarea').textcomplete([{
                match: /(^|\b)(\w{2,})$/,
                search: function (term, callback) {
                    var words = ['google', 'facebook', 'github', 'microsoft', 'yahoo'];
                    callback($.map(words, function (word) {
                        return word.indexOf(term) === 0 ? word : null;
                    }));
                },
                replace: function (word) {
                    return word + ' ';
                }
            }]);    
})(jQuery);
```

**Comment by yuku-t** [comment]
Please make sure that jquery-textcomplete.js is loaded before your code is executed.

```html
<script src='jquery.js'></script>
<script src='jquery-textcomplete.js'></script>
<script>
  // your code comes here
</script>
```

**Comment by namaljayathunga** [comment]
Yer It is sure. However I found solution. I moved bellow code set to bottom of page. But I think it is not logical solution, because that happened with js conflict. If you have any other solution, please comment. Thanks for reply.

    <script src='jquery-textcomplete.js'></script>
    <script>
    // Initialize jquery-textcomplete
    </script>

**Comment by yuku-t** [comment]
Sorry, I have no other idea.
Anyway when it comes to HTTP/1.1, loading remote javascript sources at the bottom of the document is a good practice for page speed.
