### ISSUE TITLE
Regression in dropdown position in 1.3.0+

### ISSUE THREAD

**Issue by bhollis** [yuku-t/jquery-textcomplete#239]
Commit 00f229703b3d0d46392a3245767853c9d20bdd6c introduced a regression in dropdown positioning (at least for my app). The addition of the `line-height` check on line 45 doesn't work on my site, because the element's `line-height` is `normal` (the default), which `parseInt` turns into `NaN`.

Even if that worked, I don't think it'd do what you want, since it isn't always in `px` - what if my line-height was `1.2`, or `2em`?

I understand that things were wonky for multi-line text areas, but my single-line textbox was working nicely before, and now even with a [fixed line-height function](http://stackoverflow.com/questions/4392868/javascript-find-divs-line-height-not-css-property-but-actual-line-height) it doesn't align nicely:

![image](https://cloud.githubusercontent.com/assets/313208/13976517/b6e3b046-f07d-11e5-9d8e-78e4598158b2.png)

Now, to be fair, it didn't really align perfectly before, either:

![image](https://cloud.githubusercontent.com/assets/313208/13976527/e130778a-f07d-11e5-9bd5-bb8705f36d7d.png)

And I fixed that with a `transform`, so I can just adjust that `transform` again once the `line-height` issue is solved.

Would you like a PR that incorporates that `getLineHeight` function from StackOverflow?

**Comment by yuku-t** [comment]
Hi @bhollis, thanks for opening the issue.

> because the element's `line-height` is `normal` (the default), which `parseInt` turns into `NaN`.

I understand...  :fearful: 

> Would you like a PR that incorporates that `getLineHeight` function from StackOverflow?

Yes, please :)

**Comment by yuku-t** [comment]
v1.3.2 is released and [a related sample](http://yuku-t.com/jquery-textcomplete/#input-search-element) is added to the demo.

**Comment by bhollis** [comment]
Thank you!
