### ISSUE TITLE
Input cursor doesn't move to end of inserted string on android

### ISSUE THREAD

**Issue by rgylesbedford** [yuku-t/jquery-textcomplete#24]
When using either an Android phone (HTC T-Mobile G2 running Android ver 2.3.4) or a Kindle Fire (running system ver 6.3.2_user_4110520), the cursor does not move to the end of the inserted string. The cursor stays at the position before the suggestion was selected.

**Comment by yuku-t** [comment]
Sorry for my really late reply. Because I was using iOS at that time, I couldn't reproduce the problem.
I'm not sure whether the problem has been fixed, I close the issue due to lack of any other reports. Thanks for opening the issue though!
