### ISSUE TITLE
Cannot Load textcomplete

### ISSUE THREAD

**Issue by januslinhc** [yuku-t/jquery-textcomplete#241]
<img width="1279" alt="2016-03-31 1 19 00" src="https://cloud.githubusercontent.com/assets/4537368/14166131/31addb5a-f743-11e5-96e4-1cfdb5f36096.png">

**Comment by yuku-t** [comment]
Hi @januslinhc, thanks for opening the issue.

Which version do you use?

**Comment by januslinhc** [comment]
@yuku-t
Thank you for your reply. 
my project currently is using version 1.3.2
and the libraries I haves used in my project are JQuery 2, Bootstrap and Vue.JS.

**Comment by januslinhc** [comment]
@yuku-t
$.fn.textcomplete is exit, but $.fn.textcomplete.getCaretCoordinates is not found

**Comment by januslinhc** [comment]
<img width="696" alt="2016-03-31 4 55 41" src="https://cloud.githubusercontent.com/assets/4537368/14170666/7c6db3ae-f761-11e5-8be0-d814a7a6aeeb.png">
