### ISSUE TITLE
Question: How can I make the dropdown stay fixed where it popped up

### ISSUE THREAD

**Issue by naushadjamil** [yuku-t/jquery-textcomplete#250]
Sorry - didn't find where to put a question. Please let me know so I won't create it in the issue section next time.

1. I want the popup to stay where it showed first instead of sliding as I type each character. Possible? So the end effect of this will be as the user is typing a word the dropdown is at the start of the word a little below. It can expand but not move its top/left.

Thanks!

**Comment by yuku-t** [comment]
Sorry, it is not supported.
