### ISSUE TITLE
How can I update the words through javascript

### ISSUE THREAD

**Issue by natnguyenau** [yuku-t/jquery-textcomplete#256]
Hi there

My list of words is stored in an array called availableTags which dynamically changed depends on other variables.

How can I update the words? It is not working for me at the moment

 
    $('#question_1').textcomplete([
    { // tech companies
        words: availableTags,
        match: /\b(\w{2,})$/,
        search: function (term, callback) {
            callback($.map(this.words, function (word) {
                return word.indexOf(term) === 0 ? word : null;
            }));
        },
        index: 1,
        replace: function (word) {
            return word + ' ';
        }
    }
    ]);

**Comment by yuku-t** [comment]
I think, you changed reference of `availableTags` instead of mutating the referenced array object.

You don't need to use strategy property here. Feel free to use local/global variable:

```js
var availableTags = [];

$('#question_1').textcomplete([{
  ...
  search: function (term, callback) {
    callback($.map(availableTags, function (word) {
      return word.indexOf(term) === 0 ? word : null;
    }));
  }
}]);
```
