### ISSUE TITLE
Couldn't make it work on textareas created dynamically with Ajax

### ISSUE THREAD

**Issue by 024stiv** [yuku-t/jquery-textcomplete#257]
Hi @yuku-t, good work!

I am wondering if it's our fault or textcomplete does not support dynamically created textareas with ajax.
In our project we have a modal popup loaded with ajax for posting new comments and we would like to use textcomplete here. It works on main page but not in modal.
Any help or info on this will be greatly appreciated. Thanks.

**Comment by yuku-t** [comment]
This plugin does not care when/how a textarea was created. So please make sure that the target textarea exists when you trigger this plugin.

**Comment by 024stiv** [comment]
Hey, thanks for your time and quick reply. I just checked, textarea exists before the plugin is triggered.

$(".reply_btn_top").live("click",function(){
    $.ajax({  url: "ajax.php?page=modal_add_comment",  success: function(result) 
        { 
            $("#modal").html(result).fadeIn();   //<- load ajax data(with textarea) into modal element
            $('textarea').val("x")       // <- changes textarea's value to "X" (testing to see if script can find the element)
            $('textarea').textcomplete( /*..strategies,emoji etc...*/ )     //   <- nothing happens in modal but on regular html page textcomplete is working fine with same settings`

So not sure what's going on...

**Comment by yuku-t** [comment]
If you use this plugin correctly, an `ul` element with "dropdown-menu textcomplete-dropdown" class is appended to `body` element. So please check if such `ul` element exists after the modal appears.

**Comment by 024stiv** [comment]
Thanks, finally we found the problem, it was with z-index, textcomplete dropdown was rendering behind our modal element.
