### ISSUE TITLE
.active element conflicts with Bootstrap

### ISSUE THREAD

**Issue by tomsommer** [yuku-t/jquery-textcomplete#260]
The active `<li>` gets `class="textcomplete-item active"`, but the `.active` class conflicts with Bootstrap styling. It should be changed to `.textcomplete-item-active` or something

**Comment by tomsommer** [comment]
Ignore the commit, obviously not the right fix. Issue still remains though.

**Comment by yuku-t** [comment]
You can change the dropdown element's class attribute using `dropdownClassName` option.

If you are still using the jquery-textcomplete.css (it was removed), please stop loading the file.

**Comment by tomsommer** [comment]
I am not loading the file. 

You are applying `.active` to the `<li>` element and that does not conform with bootstrap `.dropdown-menu`: http://getbootstrap.com/components/#dropdowns

I cannot change the `.active` class in config.

**Comment by yuku-t** [comment]
Bootstrap's dropdown uses `.dropdown-menu > .active > a`, NOT `.active`.

https://github.com/twbs/bootstrap/blob/v3.3.6/less/dropdowns.less#L86-L96

In addition, this plugin does not provide CSS. This means that if bootstrap dropdown is broken in your site, it is caused by another CSS written or loaded by you. Please learn the basics of CSS ahead.

**Comment by tomsommer** [comment]
Wow, awesome attitude. I know CSS. You are adding CSS classes through JavaScript, hence the problem.

The fact is that if you go through the Bootstrap documentation, `.active` is not used in .dropdown-menu, instead the `<a> `element is used for coloring.

Notice how the Bootstrap dropdowns on http://getbootstrap.com/components/#dropdowns do not look like yours, because you are adding the `.active` element to `<li>`. Can we agree these are not consistent? Nowhere is `.active` in `.dropdown-menu` documented.

**Comment by yuku-t** [comment]
Please let me see your CSS which is causing the problem.

**Comment by tomsommer** [comment]
I'm using nothing but default Bootstrap from Bower.

Even your .gif on https://github.com/yuku-t/jquery-textcomplete and the demo on http://yuku-t.com/jquery-textcomplete/ shows the selected item as blue, because of `.active`, and not grey, as seen in the official documentation on how `.dropdown-menu` is suppose to look.

**Comment by yuku-t** [comment]
`a` element in `.active` in `.dropdown-menu` has blue background-color is official behavior, even though it is not documented. It is implemented [here](https://github.com/twbs/bootstrap/blob/v3.3.6/less/dropdowns.less#L86-L96)

↓ I manually added `active` class to `li` using developer tool.

![image](https://cloud.githubusercontent.com/assets/96157/15924380/a94729a4-2e6c-11e6-8a53-a892f4fce10b.png)

If you think it is a bug, you can open an issue at https://github.com/twbs/bootstrap

---

> not grey

If you want to change the background-color of selected item to grey, use the css:

```css
.textcomplete-dropdown > .active > a {
  background-color: #f5f5f5 !important;
}
```

`#f5f5f5` came from https://github.com/twbs/bootstrap/blob/v3.3.6/less/variables.less#L248

OR if you build bootstrap css by yourself, change the [@dropdown-link-active-bg:](https://github.com/twbs/bootstrap/blob/v3.3.6/less/variables.less#L253) variable to `#f5f5f5`.
