### ISSUE TITLE
Add table support

### ISSUE THREAD

**Issue by viqtor1** [yuku-t/jquery-textcomplete#267]
I am a newbie in JavaScript/Jquery and I need help to add support for autocomplete in a td tag. I am using HandsOnTable plugin and I want do add autocomplete functionality. I've changed the properties of the cell like this: `td.setAttribute("class", "autocomplete-reports");
            td.setAttribute("contenteditable", "true");` but the behavior is not what I've expected. I would like some tips on how to add this feature, how to extend the Adapter functionality for a td tag.

**Comment by yuku-t** [comment]
Sorry, I've never used HandsOnTable plugin, and no plan to support it.
