### ISSUE TITLE
Textarea, textcomplete does not overlap.

### ISSUE THREAD

**Issue by MarsWalker** [yuku-t/jquery-textcomplete#273]
Hello to all, 
From the tests I've done textcomplete works correctly with a 
div with `contenteditable="true"` (it overlaps the control with the list).
The issue is that if you use a textarea it will show the list below the bottom of the textarea.
The textarea I'm using is the following:

```html
<div class="textareacontainer" width="80%" height="100%" >
	<textarea name="myeditor"  style="width:100%; height:50%" id="myeditor"></textarea>
</div>
```

Maybe it's not an issue and I just dont know how to use it correctly, but ... :)

![image](https://cloud.githubusercontent.com/assets/3287631/16656125/58fec7e6-4455-11e6-8a70-9d016ef795ff.png)

**Comment by yuku-t** [comment]
Styling problems depend on many many things, so it is really hard to recognize the issue without accessing your whole html and whole css.

The only thing I can suggest you is that follow the steps to figure out what causes the problem.

1. Make sure that you use the latest version.
2. Disable all css and use the plugin. Maybe it works fine.
3. Add styles step by step, and test the behaviour.

If you success to reproduce the problem, drop me a line again.
