### ISSUE TITLE
In v. 1.6.2 the height of Dropdown is calculating by itself always

### ISSUE THREAD

**Issue by joaolavoier** [yuku-t/jquery-textcomplete#276]
In the new version of the lib, the height of dropdown is calculating by the library alone, and it doesn't let me to set an height that i want, or let the height of dropdown `auto`. 

This **PR** is the cause of this problem:
https://github.com/yuku-t/jquery-textcomplete/pull/262/commits/2217f16d1837679844625ec153e67a3284c3a915

I had to download one version ago *@1.6.1* to work right.

**Comment by yuku-t** [comment]
Fixed by reverting v1.6.2 #284
