### ISSUE TITLE
Integration with CKEditor / TinyMCE

### ISSUE THREAD

**Issue by namaljayathunga** [yuku-t/jquery-textcomplete#285]
I tried to integrate jquery-textcomplete with ckeditor, then I got this error.
`TypeError: CKEDITOR.instances.issue_notes is undefined`
Can you guise give me a little help to accomplish this. I will put the code sample bellow. You can quickly look at this. Thanks.

This is jsfiddle : [https://jsfiddle.net/btjapqkp/](https://jsfiddle.net/btjapqkp/)

**Comment by amenk** [comment]
Oh my...

When I made the patch, I was integrating it into Redmine (EasyRedmine). Looks like Redmine specific code sneaked into the jquery-textcomplete - this is of course wrong. In this line, it should be the CKEDITOR instance.
I can not dig deeper into it at this moment, but maybe that helps you to make a fix?

**Comment by namaljayathunga** [comment]
Thanks @amenk, It is will be understandable for me if you can edit [jsfiddle](https://jsfiddle.net/btjapqkp/). Thanks.

**Comment by amenk** [comment]
I would have to look deeper in it - it is a bug in the textcomplete package - "proudly" introduced by me :'-(

**Comment by amenk** [comment]
@namaljayathunga Please check my patch

**Comment by namaljayathunga** [comment]
wow It's working 👍. Thanks @amenk for your quick contributing. However, there is an error when selected text replaced. check this [jsfiddle](https://jsfiddle.net/namaljayathunga/btjapqkp/4/). I'm using latest jquery-textcomplete.

**Comment by amenk** [comment]
Did you rebuild jquery-textcomplete? In my pull request I changed only the src/ folder - not dist/.
Additionally in the fiddle I think you should call textcomplete on the CKEditor textarea first before intialize the CKeditor.

**Comment by amenk** [comment]
Okay .. It is working, as long as there are not so much other edits on the page:
https://jsfiddle.net/btjapqkp/8/
Further PRs are appreciated :)

**Comment by namaljayathunga** [comment]
Thanks a lot @amenk for dedicate your value time. using ID as a selector, I could use more editor.
