### ISSUE TITLE
Overflow mechanism for more than maxCount completions

### ISSUE THREAD

**Issue by petsuter** [yuku-t/jquery-textcomplete#290]
Currently `maxCount` is a hard limit to the number of shown elements. Additional elements are discarded without any indication to the user.

It would be nice if there was an indication that additional elements are available (maybe show a `...` ellipsis?) and even nicer if the user could somehow use those additional elements (maybe by scrolling through the list?) even if still only a limited number of elements is visible at once.

**Comment by yuku-t** [comment]
You can do that by overriding `max-height` of `.textcomplete-dropdown` and set huge number to `maxCount`.

**Comment by petsuter** [comment]
Ah, ok that works great, thanks a lot! I guess this issue can be closed then.

(We use jquery-textcomplete in [this plugin](https://trac-hacks.org/wiki/WikiAutoCompletePlugin) for the *Trac* issue tracker and wiki system. It works great! Many thanks for writing it.

We'll use [this CSS](https://trac-hacks.org/ticket/12925#comment:3)  as suggested.)
