### ISSUE TITLE
Pressing tab key to select suggestion and continue with more suggestions doesn't work anymore

### ISSUE THREAD

**Issue by petsuter** [yuku-t/jquery-textcomplete#291]
Before #212, the Tab key could be used to select a partial suggestion and then continue with more suggestions.
Now it just does the same thing as Enter (select suggestion and close menu) instead of showing a new menu with sub-suggestions.
How can I get back the old behavior?

Thanks.

**Comment by yuku-t** [comment]
It is intended behavior. If you need old behavior, revert d5e5aea4c3113a036d5e1069b96a3c13ce992ff2 by yourself
