### ISSUE TITLE
Problem accent

### ISSUE THREAD

**Issue by bopel** [yuku-t/jquery-textcomplete#297]
When I use this script as on the demo page, with this example : 
_var words = ['google', 'facebook', 'github', 'microsoft', '**ingénieur**'];_
if I type "ing", it works fine but if I type "ingé" (french word), the "é" stops the srcipt.
Do you have any idea how to solve this problem
Thanks

**Comment by aMarCruz** [comment]
@bopel , you need to change `/\b(\w{2,})$/` to `/\b([\w\xA0-\xFF]{2,})$/` in the regex of the `match` property to include accented characters from the iso-8859 charset (8 bits only).
