### ISSUE TITLE
Emojies?

### ISSUE THREAD

**Issue by bill-mybiz** [yuku-t/jquery-textcomplete#298]
I see in your examples that you are mapping an array variable called `emojies`. I've forked the repo and I can't find any reference to these, nor any references to the actual png's. Could you share how you created your demo and animated gifs on the README? Or is there just something obvious that I'm missing?

**Comment by yuku-t** [comment]
- https://github.com/yuku-t/jquery-textcomplete/blob/gh-pages/media/javascripts/emoji.js

I created the array using [GitHub Emojis API](https://developer.github.com/v3/emojis/)
