### ISSUE TITLE
one function with two different search results

### ISSUE THREAD

**Issue by wipau** [yuku-t/jquery-textcomplete#71]
can  we make like this ?? i wan to make like this
![onetextcompletewithtwodifferentsearchtype](https://cloud.githubusercontent.com/assets/3582208/2753262/28cdcabc-c92e-11e3-95af-987e1f1a5b34.jpg)
this picture from twitter

**Comment by yuku-t** [comment]
Sorry for my late reply. I considered the proposed feature, but I think it is really hard to support it because some search function callbacks in async manner. Maybe your workflow is the bast way to do it. Thanks for the comment!
