### ISSUE TITLE
A few issues I've encountered

### ISSUE THREAD

**Issue by shawn-simon** [yuku-t/jquery-textcomplete#77]
Hey, I've been using your jquery textcomplete for a few weeks now and it's really good. However, there are several issues with it that I've fixed but not sure if it's good enough to submit back.

1. The $baseWrapper should be attached to the end of the body, and not wrap the actual element. There's no real reason to wrap the element, and often contenteditable will be on the body of an iframe, for example, a ckeditor. Wrapping the textareas, etc can also break selectors, or be hidden by overflow: hidden.

2. References to window, instead of this.el.ownerDocument. Often, contenteditables will be in an iframe, so document.activeElement / window.getSelection() will not refer to the correct frame.

3. The list of properties to copy in getCaretPosition should include 'box-sizing' and 'tab-size' as well. The base css should include 'word-wrap': 'break-word' since I believe that's the default for textareas.

4. The logic for getCaretPosition inside a content editable (starting at line 378) is massively wrong. First, there's no need to clone the range in line 378. Selecting the node contents and deleting them doesn't seem to do anything. Third, it leaves behind empty span tags in IE, which changes the current selection in the window. It winds up completely breaking textcomplete in IE9+ (it winds up calling deleteNodeContents on the wrapper of wherever your typing, wiping out images, links, etc). I spent 3 days figuring this out : ( Furthermore, I don't think you need to even insert a span tag when getSelection is present since there's a method on the range to get the position. This is probably the biggest issue.

5. No scrolling support for dropdown. I added the ability for the list to scroll so if you have more than 20 results, you can page up / down through them, and scroll the bar.

6. Calling destroy on a textarea inside an iframe somehow breaks in IE. I think because the destroy event comes from within the iframe.

7. Doesn't seem to work in IE8 for me. This is the next thing I'm working on. edit: giving up on this lol.

Anyway I was able to fix everything but IE8 and it works quite well. Here's a gist of the changes I've made, but they're pretty hacky:

https://gist.github.com/shawn-simon/c45152770da94d0c6d83

**Comment by kjhangiani** [comment]
Hi guys,

First off - big thanks to both of you.  The jquery-textcomplete plugin is fantastic, and we make good use of it in our app.  I love the flexibility of it, and it's very clean.

We ran into the same issue as @shawn-simon, particularly in regards to using the component with a rich textarea, such as CKEditor or TinyMCE.  These editors typically use an iframe with a body contenteditable element, and the plugin didn't seem to like that.

#2 on the list above in particular was a pain point for us.

I just spent a bunch of time trying to resolve this on the latest version, and I finally got it to work.  I had to deploy this as I am going out of town for a few days, so apologies for not making a pull request, I'll do that next week if you need.

In the interim, I forked the project, and made the changes here (squashed to a single commit):

https://github.com/soxhub/jquery-textcomplete/commit/89729d4a5cfc0046d5c18290c9498e2fd38799dd

This seems to work for me with TinyMCE, mostly the logic is related to altering the position if the input element is detected to be in an iframe.  I haven't tested this fully so I can't guarantee its stability, but it is working for us right now.

Thanks again!

**Comment by yuku-t** [comment]
I started implementing v2 with completely new code base. In addition Microsoft finished their IE8 support, so I close the issue. Thanks for the comments though!

**Comment by temuri416** [comment]
@yuku-t Looking forward to the new version!

Cheers.
