### ISSUE TITLE
dropdown-menu caret positioning calculations are off

### ISSUE THREAD

**Issue by chandrewz** [yuku-t/jquery-textcomplete#83]
When using this plugin in my app, the menu with suggestions end up in random places on the screen, so it seems like the caret calculations are off. I was able to do it on the demo page too.

![screenshot 2014-05-29 10 46 01](https://cloud.githubusercontent.com/assets/6334216/3119627/a70cb68a-e748-11e3-9cb5-f7cecfb634a1.png)

Maybe Caret.js could help? (http://ichord.github.io/Caret.js/)

**Comment by p4d** [comment]
Got the same error on my pages.. But when i go to the Demo page, the problem seems to not be present on the demo page.. Can you explain us why ?

**Comment by yuku-t** [comment]
@p4d It strongly depends on your project, I cannot explain why it happens.

**Comment by p4d** [comment]
Ok, it seems you are right.. I did not found any common point between your demo and my code on my example.. I'm gonna try to integrate caretjs and then use it inside your plugin in order to make it find size clean wether the conditions are different or not. I'll try to update it if it works.

**Comment by yuku-t** [comment]
@p4d I'm writing v2. The version uses external core module: [yuku-t/textcomplete](http://github.com/yuku-t/textcomplete) [[demo](http://yuku-t.com/textcomplete/)]. It already using caretjs.
If you don't care lack of IE8 support, you can use it.

**Comment by yuku-t** [comment]
Now v1.2.2 is released, which uses textarea-caret npm package. please use the new version.
